import type { GenerateSchema } from 'payload'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { existsSync } from 'node:fs'

import type { DynamoAdapter } from './types.js'

import { buildCreateTableInput, ENTITY_KEY_TEMPLATES, TABLE_KEY_ATTRS } from './schema/tableDefinition.js'
import { collectPointFields, collectIndexPaths } from './schema/collectFields.js'

export const generateSchema: GenerateSchema = async function generateSchema(
  this: DynamoAdapter,
  { log = true, outputFile, prettify = true } = {},
) {
  const tableName = this.tableName
  const createTable = buildCreateTableInput(tableName)

  const collections = Object.values(this.payload.collections).map((c) => ({
    slug: c.config.slug,
    indexes: collectIndexPaths(c.config),
    pointFields: collectPointFields(c.config.fields),
    versions: Boolean(c.config.versions),
    drafts: Boolean(c.config.versions?.drafts),
  }))

  const globals = this.payload.config.globals.map((g) => ({
    slug: g.slug,
    pointFields: collectPointFields(g.fields),
    versions: Boolean(g.versions),
  }))

  const schemaDocument = {
    tableName,
    keys: TABLE_KEY_ATTRS,
    entityKeyTemplates: ENTITY_KEY_TEMPLATES,
    createTable,
    collections,
    globals,
  }

  let resolvedOutput = outputFile
  if (!resolvedOutput) {
    const cwd = process.cwd()
    const srcDir = path.resolve(cwd, 'src')
    resolvedOutput = existsSync(srcDir)
      ? path.resolve(srcDir, 'payload-generated-dynamodb.json')
      : path.resolve(cwd, 'payload-generated-dynamodb.json')
  }

  let content = JSON.stringify(schemaDocument, null, prettify ? 2 : 0)

  if (prettify && resolvedOutput.endsWith('.ts')) {
    content = [
      '/* eslint-disable */',
      '/** Auto-generated by @payloadcms/db-dynamodb — do not edit by hand. */',
      `export const payloadGeneratedDynamodb = ${JSON.stringify(schemaDocument, null, 2)} as const`,
      '',
      'declare module "@payloadcms/db-dynamodb" {',
      '  export interface GeneratedDatabaseSchema {',
      '    schema: typeof payloadGeneratedDynamodb',
      '  }',
      '}',
      '',
    ].join('\n')
  }

  await writeFile(resolvedOutput, content, 'utf-8')

  if (log) {
    this.payload.logger.info(`Written ${resolvedOutput}`)
  }
}
